#!/bin/bash
dir=/mnt/pmem1-node0/pool1
num=8
perf_dir=./insert_perf/
loadsize=50000000
FLAG='-mavx -mavx2 -mavx512f -mavx512bw -mavx512vl'  
outdir=./sendata
srcdir=./sensitive.cpp
for testnum in 1 2 3 4 5
do
    for sbucketsize in 64 128 256 512 1024
    do
        sed -i '27d' ./src/ElimDA.h
        sed -i '27i #define S_Bucket_Size '$sbucketsize'' ./src/ElimDA.h
        rm -rf $dir
        g++ -O3 -std=c++17 -I./ -lrt -c -o src/ElimDA.o -g src/ElimDA.cpp -DINPLACE -lpmemobj -lpmem $FLAG -lprofiler -lunwind
        g++ -O3 -std=c++17 -I./ -lrt  -o bin/multi_threaded_ElimDA -g src/test.cpp src/ElimDA.o include/dlock.o  -lpmemobj -lpmem -lpthread -DMULTITHREAD -lpqos 
        numactl -N 0 -m 0 \
        ./bin/multi_threaded_ElimDA $dir $loadsize $num |grep -a "Ops/sec" >> $outdir
    done
    sed -i '27d' ./src/ElimDA.h
    sed -i '27i #define S_Bucket_Size 256' ./src/ElimDA.h
done