#!/bin/bash
dir=/mnt/pmem1-node0/pool1
perf_dir=./insert_perf/
loadsize=50000000
runsize=50000000
FLAG='-mavx -mavx2 -mavx512f -mavx512bw -mavx512vl'  
g++ -O3 -std=c++17 -I./ -lrt -c -o src/ElimDA.o -g src/ElimDA.cpp -DINPLACE -lpmemobj -lpmem $FLAG -lprofiler -lunwind 
g++ -O3 -std=c++17 -I./ -lrt  -o bin/run_all_ycsb -g src/run_all_ycsb.cpp src/ElimDA.o include/dlock.o  -lpmemobj -lpmem -lpthread -DMULTITHREAD -lpqos 
outdir=ycsb_all
for test in 1 2 3 4
do
    for oper in "w50r50.txt" "u50r50.txt" "w5r95.txt" "u5r95.txt"
    do
        for num in 1 2 4 8 16 24
        do
            echo " " >> $outdir
            echo "test zipfian  "$num" "$oper >> $outdir
            ycsb_dir="../ycsb/zipfian/"$oper
            load_dir="../ycsb/zipfian/load.txt"
            rm -rf $dir
            numactl -N 0 -m 0 \
            ./bin/run_all_ycsb $dir $loadsize $runsize $num $ycsb_dir $load_dir  |grep -a -E "num|Ops|Start" >> $outdir   
        done
    done
done
